inputs:
  PREFIX_NAME:
    required: true
  IMAGE_TAG:
    required: true
  HELM_VALUES_ARG:
    required: true
  TIMEOUT:
    required: false
    default: "5m"
  ACTION:
    required: true

outputs:
  INGRESS_HOSTS_JSON:
    description: "JSON of Ingress hosts"
    value: ${{ steps.main.outputs.INGRESS_HOSTS_JSON }}

runs:
  using: "composite"
  steps:
    #- name: Checkout code
    #  uses: actions/checkout@v2

    ## For debug only
    #- shell: bash
    #  run: |
    #    base64 <<EOF
    #    ${{ toJSON(inputs) }}
    #    EOF
    #- shell: bash
    #  run: |
    #    env | sort
    - shell: bash
      id: main
      # a checkout action of `coopTilleuls/action-helm` must be set with `path: 'action-helm'`
      run: |
        set -e
        cd action-helm
        bash script.sh
        echo "githubé té teubé ou pas ?"
        echo "INGRESS_HOSTS_JSON=${INGRESS_HOSTS_JSON}" >> $GITHUB_OUTPUT
        # TODO: rm debug
        echo $GITHUB_OUTPUT
      env:
        PREFIX_NAME: ${{ inputs.PREFIX_NAME }}
        ACTION: ${{ inputs.ACTION }}
        TIMEOUT: ${{ inputs.TIMEOUT }}
        HELM_VALUES_ARG: ${{ inputs.HELM_VALUES_ARG }}










